### ISSUE TITLE
suggestion: use git-lfs for large files in git

### ISSUE THREAD

**Issue by mmdaz** [aut-ce/rawdata#1]
I suggest you use the git-lfs as a solution for large files in git. :D
You can see this link for GitHub:
https://git-lfs.github.com/

**Comment by aliemo** [comment]
Absolutely yes, but usually the files are not huge. Its content depends on the course holder, instructor, and semester.
The goal is for all instructors able to proceed simply and delegate the task to each other.

Thanks :)
